[package]
name = "mutagen"
version = "0.1.0"
authors = ["Josh Hebert <jhebes7@gmail.com>"]

[dependencies]
toml = "*"
rust-lzma = "0.2"
tar = "0.4"
libc = "0.2"
fuse = "0.3.0"
time = "*"
rustc-serialize = "*"
